import React, { useState } from "react";
import "../Subscription.css";

function MarketingDashboard() {
  const [campaigns, setCampaigns] = useState([
    { id: 1, name: "Spring Sale", budget: 5000, status: "Active", conversions: 0 },
    { id: 2, name: "Summer Launch", budget: 8000, status: "Planned", conversions: 0 },
  ]);

  const [leads, setLeads] = useState([
    { id: 1, name: "John Doe", email: "john@example.com", stage: "New" },
    { id: 2, name: "Jane Smith", email: "jane@example.com", stage: "Contacted" },
  ]);

  const [roiData, setRoiData] = useState({ totalSpent: 13000, revenue: 30000 });
  const [reports, setReports] = useState([]);
  const [socialPosts, setSocialPosts] = useState([]);
  const [seoScore, setSeoScore] = useState(75);
  const [keywords, setKeywords] = useState(["AI", "Marketing", "Growth"]);
  const [content, setContent] = useState([]);
  const [notifications, setNotifications] = useState([]);
  const [crmTasks, setCrmTasks] = useState([]);
  const [customerJourney, setCustomerJourney] = useState([]);
  const [chatbotLogs, setChatbotLogs] = useState([]);
  const [events, setEvents] = useState([]);

  // -------------------- Functionalities --------------------
  const handleVoiceCommand = () => {
    const suggestion = "AI suggests increasing ad budget for Spring Sale!";
    console.log(suggestion);
    alert(suggestion);
  };

  const addCampaign = () => {
    const newCampaign = { id: campaigns.length + 1, name: "New Campaign", budget: 2000, status: "Planned", conversions: 0 };
    setCampaigns([...campaigns, newCampaign]);
  };

  const analyzeROI = () => {
    const roi = ((roiData.revenue - roiData.totalSpent) / roiData.totalSpent) * 100;
    alert(`Current ROI: ${roi.toFixed(2)}%`);
  };

  const segmentLeads = () => {
    const newLeads = leads.map(l => ({ ...l, stage: "Segmented" }));
    setLeads(newLeads);
    alert("Leads segmented successfully!");
  };

  const generateReport = () => {
    const report = `Report ${reports.length + 1}: ${new Date().toLocaleDateString()}`;
    setReports([...reports, report]);
    alert("Report generated: " + report);
  };

  const sendEmailBlast = () => {
    alert(`Email sent to ${leads.length} leads!`);
  };

  const scheduleSocialPost = () => {
    const post = `Post ${socialPosts.length + 1} scheduled at ${new Date().toLocaleTimeString()}`;
    setSocialPosts([...socialPosts, post]);
    alert(post);
  };

  const viewTrends = () => {
    alert("Market trends: AI, Automation, Sustainability rising!");
  };

  const updateBudget = (id, newBudget = 1000) => {
    const updated = campaigns.map(c => c.id === id ? { ...c, budget: newBudget } : c);
    setCampaigns(updated);
  };

  const trackConversions = (id) => {
    const updated = campaigns.map(c => c.id === id ? { ...c, conversions: c.conversions + Math.floor(Math.random() * 50) } : c);
    setCampaigns(updated);
  };

  const assignLeads = () => {
    alert("Leads assigned to sales reps!");
  };

  const trackEngagement = () => {
    alert("Engagement metrics tracked successfully!");
  };

  const forecastSales = () => {
    const forecast = roiData.revenue * 1.1;
    alert(`Forecasted Revenue: $${forecast.toFixed(0)}`);
  };

  const optimizeAds = () => {
    alert("Ads optimized using AI suggestions!");
  };

  const viewCompetitors = () => {
    alert("Competitor analysis completed!");
  };

  const manageSEO = () => {
    const newScore = Math.min(100, seoScore + 5);
    setSeoScore(newScore);
    alert(`SEO score improved to ${newScore}`);
  };

  const generateContent = () => {
    const newContent = `Content ${content.length + 1} generated by AI`;
    setContent([...content, newContent]);
    alert(newContent);
  };

  const automateReports = () => {
    generateReport();
    alert("Reports automated!");
  };

  const analyzeKeywords = () => {
    alert(`Keywords analyzed: ${keywords.join(", ")}`);
  };

  const trackEmailMetrics = () => {
    alert("Email open rate: 42%, CTR: 8%");
  };

  const pushNotifications = () => {
    const notification = `Notification ${notifications.length + 1} sent!`;
    setNotifications([...notifications, notification]);
  };

  const crmIntegration = () => {
    setCrmTasks([...crmTasks, "New CRM Task"]);
    alert("CRM integration completed!");
  };

  const trackCustomerJourney = () => {
    setCustomerJourney([...customerJourney, `Customer visited page at ${new Date().toLocaleTimeString()}`]);
    alert("Customer journey tracked!");
  };

  const chatbotInsights = () => {
    setChatbotLogs([...chatbotLogs, `Chatbot interaction at ${new Date().toLocaleTimeString()}`]);
    alert("Chatbot insights logged!");
  };

  const trackSocialMentions = () => {
    alert("Tracked 15 social media mentions today!");
  };

  const manageEvents = () => {
    const newEvent = { id: events.length + 1, name: "Webinar", date: new Date().toLocaleDateString() };
    setEvents([...events, newEvent]);
    alert("Event added: " + newEvent.name);
  };

  return (
    <div className="marketing-dashboard">
      <h1>Marketing Dashboard</h1>

      {/* Campaigns */}
      <section className="section">
        <h2>Campaign Overview</h2>
        {campaigns.map((c) => (
          <div key={c.id} className="card">
            <h3>{c.name}</h3>
            <p>Budget: ${c.budget}</p>
            <p>Status: {c.status}</p>
            <p>Conversions: {c.conversions}</p>
            <button onClick={() => updateBudget(c.id)}>Update Budget</button>
            <button onClick={() => trackConversions(c.id)}>Track Conversions</button>
          </div>
        ))}
        <button onClick={addCampaign} className="primary-btn">➕ Add Campaign</button>
      </section>

      {/* Leads */}
      <section className="section">
        <h2>Leads & Segmentation</h2>
        {leads.map((l) => (
          <div key={l.id} className="card">
            <p>{l.name} ({l.email}) - {l.stage}</p>
            <button onClick={assignLeads}>Assign</button>
            <button onClick={segmentLeads}>Segment</button>
          </div>
        ))}
      </section>

      {/* ROI */}
      <section className="section">
        <h2>ROI & Budget Insights</h2>
        <p>Total Spent: ${roiData.totalSpent}</p>
        <p>Revenue: ${roiData.revenue}</p>
        <button onClick={analyzeROI}>Analyze ROI</button>
      </section>

      {/* AI Tools */}
      <section className="section">
        <h2>AI Tools & Automation</h2>
        <div className="tools-grid">
          <button onClick={handleVoiceCommand}>🎤 Ask AI</button>
          <button onClick={generateReport}>Generate Report</button>
          <button onClick={sendEmailBlast}>Email Blast</button>
          <button onClick={scheduleSocialPost}>Schedule Social Post</button>
          <button onClick={viewTrends}>View Trends</button>
          <button onClick={forecastSales}>Forecast Sales</button>
          <button onClick={optimizeAds}>Optimize Ads</button>
          <button onClick={viewCompetitors}>Competitor Analysis</button>
          <button onClick={manageSEO}>SEO Audit</button>
          <button onClick={generateContent}>Content Generation</button>
          <button onClick={automateReports}>Automate Reports</button>
          <button onClick={analyzeKeywords}>Keyword Analysis</button>
          <button onClick={trackEmailMetrics}>Email Metrics</button>
          <button onClick={pushNotifications}>Push Notifications</button>
          <button onClick={crmIntegration}>CRM Integration</button>
          <button onClick={trackCustomerJourney}>Customer Journey</button>
          <button onClick={chatbotInsights}>Chatbot Insights</button>
          <button onClick={trackSocialMentions}>Social Mentions</button>
          <button onClick={manageEvents}>Manage Events</button>
        </div>
      </section>
    </div>
  );
}

export default MarketingDashboard;